; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{659F9344-6818-4D60-8D06-630552F16595}
AppName=POSvrSys
AppVerName=POSvrSys 0.1
AppPublisher=b3rx Technologies
AppPublisherURL=http://posvrsys.googlecode.com
AppSupportURL=http://posvrsys.googlecode.com
AppUpdatesURL=http://posvrsys.googlecode.com
DefaultDirName={pf}\POSvrSys
DefaultGroupName=POSvrSys
AllowNoIcons=yes
LicenseFile=..\COPYING
OutputBaseFilename=POSvrSys 0.1 Setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\dist\posvrsys.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\POSvrSys"; Filename: "{app}\posvrsys.exe"
Name: "{group}\{cm:UninstallProgram,POSvrSys}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\POSvrSys"; Filename: "{app}\posvrsys.exe"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\POSvrSys"; Filename: "{app}\posvrsys.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\posvrsys.exe"; Description: "{cm:LaunchProgram,POSvrSys}"; Flags: nowait postinstall skipifsilent

